### ISSUE TITLE
76 CVE issues in all wodby images using gotpl

### ISSUE THREAD

**Issue by heyyo-droid** [wodby/gotpl#2]
We just tested if wodby images had any CVE issue.

It looks like all wodby images, have the same vulnerabilities, coming from gotpl binary.

I suppose the version of `go` should be updated regularly before compiling gotpl.

```
stdlib 1.16
pkg:golang/stdlib@1.16
```

![image](https://github.com/user-attachments/assets/0a4dda1d-b556-4665-a94b-1409446ba347)

**Comment by heyyo-droid** [comment]
Wouah you are awesome man !

**Comment by csandanov** [comment]
Thank you! updated go to 1.23 now
